In [2]:
import numpy as np
from scipy import sparse

x=np.array([[1,2,3],[4,5,6]])
print("x:\n",x)

x:
 [[1 2 3]
 [4 5 6]]


In [3]:
y=np.array([[4,5,6],[7,8,9]])
print(y)

[[4 5 6]
 [7 8 9]]


In [10]:
%matplotlib inline
import matplotlib.pyplot as plt

x=np.linspace(0,10,10)

y=np.cos(x)

plt.plot(x,y,marker=".")

In [13]:
import pandas as pd

data={'Name':['john','ann','peter','linda'],
      'Location':['a','b','c','d'],
      'Age':[1,2,3,4]}
data_pandas=pd.DataFrame(data)
data_pandas[data_pandas.Age>2]

Name Location  Age
2  peter        c    3
3  linda        d    4